name: safeplus
description: "Student Safety & Support System - SafePulse App."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # --- Backend & Auth ---
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6
  
  # --- Maps & Location ---
  geolocator: ^14.0.2
  google_maps_flutter: ^2.14.2
  geocoding: ^4.0.0
  
  # --- Advanced Security Features ---
  shake: ^3.0.0
  permission_handler: ^12.0.1
  flutter_local_notifications: ^20.1.0
  flutter_background_service: ^5.1.0
  
  # --- System Utilities ---
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  image_picker: ^1.2.1
  provider: ^6.1.5+1
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # --- මෙන්න මෙතන තමයි සිතියමේ රූපය Register වෙලා තියෙන්නේ ---
  assets:
    - assets/images/sliit_map.png
    - assets/sounds/iphone_ringtone.mp3